default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: comercial
  username: pamela
  password: pamela
  host: 10.20.100.38

test:
  <<: *default
  database: gsan_cadastro_api_test
  username: <%= ENV['DB_TEST_USER'] %>
  password: <%= ENV['DB_TEST_PASSWORD'] %>

production:
  <<: *default
  database: gsan_cadastro_api_production
  username: gsan_cadastro_api
  password: <%= ENV['GSAN_CADASTRO_API_DATABASE_PASSWORD'] %>
