# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 775204bd489c109320fb9fd7ddf016aef766c63d0eb2eef2cdb32e900573c3de583371763c15dd2826c2b15d4a1556829cae15ad5b8dae0e619312ec8feb6c04

test:
  secret_key_base: fe52600eb570ff91016d6c7cb98f7c741fe9bef749d6745911e7d1bc7bbf0b75af8a5a08a731e13fdea9855a3bf8538f5cc67c4eb8845e3c3e8d9396ad35f234

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
